#!/usr/bin/env python
import os
print ("CREDITOS AL DEVELOPER")
print ("CREADOR: ElBossC")
print ("DATE: 16/09/2022")
print ("TELEGRAM: https://t.me/@ElBossC")
print ("MENSAJE: Nunca dejes de aprender compita")
print ("")

raw_input("Presiona enter para continuar")
os.system("python2 cc-genpro2.0.py")
